services:
  postgres:
    image: postgres:latest
    container_name: finance_postgres
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: finance_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local